#!/usr/bin/env bash
set -e

COMMAND_NAME="$(exec basename "$0")"

if ! hash aliases 2>/dev/null; then
  echo "aliases command doesn't exists, can't continue"
  exit 1
fi

if aliases list --local --name "$COMMAND_NAME" >/dev/null 2>&1; then
  aliases exec "$(pwd -P)" "$COMMAND_NAME" -- "$@"
elif aliases list --directory "$HOME" --name "$COMMAND_NAME" >/dev/null 2>&1; then
  aliases exec "$HOME" "$COMMAND_NAME" -- "$@"
else
  PATH=${PATH/$HOME\/.aliases.d\/shims:/} # remove shims from path

  if hash $COMMAND_NAME 2>/dev/null; then
    exec "$COMMAND_NAME" "$@"
  else
    echo "No alias '$COMMAND_NAME' available in this directory"
    exit 1
  fi

fi
